@startuml State_Diagram
[*] --> MainMenu : App Start

state MainMenu {
    [*] --> EmulationTab : Default
    EmulationTab --> MemoryViewerTab : Click "Memory Viewer"
    EmulationTab --> CpuViewerTab : Click "CPU Viewer"
    EmulationTab --> FileChooserTab : Click "Load file"
}

MainMenu --> SettingsDialog : Click "Settings"
SettingsDialog --> MainMenu : Close Dialog

MainMenu --> Exit : Click "Exit"
Exit --> [*]
@enduml
